config/routes.rb
Rails.application.routes.draw do
  get 'matchups/index'

  get 'matchups/show'

  get 'matchups/create'
  post 'matchups/create'

  get 'matchups/lineup'
  post 'matchups/lineup'

  get 'games/index'

  get 'teams/index'

  devise_for :users
  root 'pages#home'
  get 'pages/about'
  get 'users/sign_in'

  resources :teams
  resources :games
  resources :matchups

end

app/models/game.rb
class Game < ActiveRecord::Base
    has_and_belongs_to_many :teams

    def display
        "#{home} @ #{away} on #{game_time}"
    end

end

app/models/matchup.rb
class Matchup < ActiveRecord::Base
    validates_presence_of :challengee
end

app/models/player.rb
class Player < ActiveRecord::Base
    belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
    has_and_belongs_to_many :games
    has_many :players
    self.primary_key = "name"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
      @games = Game.all.order(:game_time)
  end
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @matchup = Matchup.new
    @matchup.team = params[:matchup][:team]
  end


  def lineup
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
      @matchup = Matchup.new
      @teams = Team.all.order(:name)
  end
  def about
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def home
	end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
      @teams = Team.all.order(:name)
  end

  def show
      @players = Team.find(params[:id]).players
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matchup_helper.rb
module MatchupHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<table>
<% @games.each do |game| %>
    <tr>
        <td><%= link_to game.away, team_path(game.away) %> @  <%= link_to game.home, team_path(game.home) %></td><td> <%= game.game_time.in_time_zone("Eastern Time (US & Canada)").strftime "%B %-d, %Y @ %I:%M %p"  %></td>
</tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CouchMVP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<!-- Template References [Input by MK] -->
  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="img/favicon.png">

  <!-- Bootstrap core CSS -->
  <!--<link href="css/bootstrap.css" rel="stylesheet">-->

  <!-- Custom styles for this template -->
  <!--<link href="css/color-styles.css" rel="stylesheet">-->
  <!--<link href="css/ui-elements.css" rel="stylesheet">
  <link href="css/custom.css" rel="stylesheet">-->
  
  <!-- Resources -->
  <!--<link href="css/animate.css" rel="stylesheet">-->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,500,400italic,500italic,700italic' rel='stylesheet' type='text/css'>

</head>
<body>

  <body class="body-green">
  
    <div class="navbar navbar-dark navbar-static-top" role="navigation">
      <div class="container">
    
      <!-- Navbar Header -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "CouchMVP".html_safe , root_url, class: "navbar-brand" %>
        </div> <!-- / Navbar Header -->

      <!-- Navbar Links -->
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", root_url, class: "bg-hover-color" %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "bg-hover-color" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path, class: "bg-hover-color" %></li>
              <li><%= link_to "Sign up", new_user_registration_path, class: "bg-hover-color" %></li>
            <% end %>
          </ul>
      
      <!-- Search Form (xs) -->
      <form class="navbar-form navbar-left visible-xs" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Go!</button>
      </form> <!-- / Search Form (xs) -->
  
        </div> <!-- / Navbar Links -->
      </div> <!-- / container -->
    </div> <!-- / navbar -->

	<%= yield %>

<!-- Footer -->
  <footer class="footer-dark">
    <div class="container">
      <div class="row">
        <!-- Contact Us -->
        <div class="col-sm-4">
        <h3 class="text-color"><span class="border-color">Contact Us</span></h3>
        <div class="content">
        <p>
        Email: <a href="#">support@couchmvp.co</a>
        </p>
        </div>
      </div>
      <!-- Social icons -->
        <div class="col-sm-4">
        <h3 class="text-color"><span>Go Social</span></h3>
        <div class="content social">
        <p>Stay in touch with us:</p>
        <ul class="list-inline">
        <li><a href="https://twitter.com/CouchMVP" class="twitter"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#" class="github"><i class="fa fa-github"></i></a></li>
        <li><a href="#" class="plus"><i class="fa fa-google-plus"></i></a></li>
        </ul>
        <div class="clearfix"></div>
        </div>
      </div>
      <!-- Subscribe -->
        <div class="col-sm-4">
        <h3 class="text-color"><span>Subscribe</span></h3>
        <div class="content">
            <p>Enter your e-mail below to subscribe to updates about CouchMVP!</p>
        <form class="form" role="form">
          <div class="row">
            <div class="col-sm-8">
            <div class="input-group">
            <label class="sr-only" for="subscribe-email">Email address</label>
            <input type="email" class="form-control" id="subscribe-email" placeholder="Enter email">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default">OK</button>
            </span>
            </div>
            </div>
          </div>
        </form>
        </div>
      </div>
      </div>
    <div class="row">
      <div class="col-sm-12">
        <hr>
      </div>
    </div>
    <!-- Copyrights -->
      <div class="row">
        <div class="col-sm-12">
            <p>&copy; CouchMVP 2014.</p>
      </div>
      </div>
    </div>
  </footer>
  
  
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <!--<script src="js/bootstrap.min.js"></script>
    <script src="js/scrolltopcontrol.js"></script>
    <script src="js/jquery.sticky.js"></script>
    <script src="js/custom.js"></script>-->

</body>
</html>

app/views/matchups/create.html.erb
<h1>Matchup#create</h1>
<p>Find me in app/views/matchup/create.html.erb</p>

            <%= form_for @matchup, url: "lineup" do |f| %>
<!--                <%= f.text_field :challenger %>
<%= f.text_field :challengee %> -->
                <%= f.collection_select(:game_id, Game.all.where("home = ? OR away = ?", @matchup.team, @matchup.team).order(:game_time), :id, :display) %>
                <%= f.submit "Next" %>
             <% end %>

app/views/matchups/index.html.erb
<h1>Matchup#index</h1>
<p>Find me in app/views/matchup/index.html.erb</p>

app/views/matchups/lineup.html.erb
<h1>Matchup#lineup</h1>
lineup stuff here

app/views/matchups/show.html.erb
<h1>Matchup#show</h1>
<p>Find me in app/views/matchup/show.html.erb</p>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/gamestart.html.erb
<!-- Wrapper -->
	<div class="wrapper">
	
	  <!-- Topic Header -->
	  <div class="topic">
	    <div class="container">
		  <div class="row">
		    <div class="col-sm-4">
		      <h3 class="primary-font">Start Game</h3>
		    </div>
		    <div class="col-sm-8">
		      <ol class="breadcrumb pull-right hidden-xs">
		        <li><a href="index.html">Home</a></li>
		        <li class="active">Start Game</li>
		      </ol>
		    </div>
	      </div>
		</div>
	  </div>
	  
	  <div class="container">
	    <div class="row">
		  <div class="col-sm-12">
			<div class="sign-form">
			  <h3 class="first-child">Denver Broncos</h3>
			  <h4 class="second-child">vs. Indianapolis, September 7th, 2014</h4>
			  <hr>
			  <table class="table table-striped table-responsive">
			  	<thead>
			  		<tr>
			  			<th>Position</th>
			  			<th>Player Name</th>
			  			<th>Prediction</th>
			  		</tr>
			  	</thead>
			  	
<!-- Depending on form selected on authenticated
home page, players will needed to be generated within HTML structured as such -->
			<form>
			  	<tbody>
			  		<tr>
			  			<td>QB</td>
			  			<td>Peyton Manning</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>RB1</td>
			  			<td>Monte Ball</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>RB2</td>
			  			<td>Anderson</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>WR1</td>
			  			<td>Demarius Thomas</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>WR2</td>
			  			<td>Emmanuel Sanders</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>WR3</td>
			  			<td>Wes Welker</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>TE1</td>
			  			<td>Julius Thomas</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>

			  		<tr>
			  			<td>K</td>
			  			<td>Matt Praeter</td>
			  			<td><input type="QB" class="form-control" id="email" placeholder="Prediction" data-original-title="" title=""></td>
			  		</tr>			  	

			  	</tbody>
			 </form>

			</table>	

			  <form role="form">
			    <button type="submit" class="btn btn-color">Submit</button>
				<hr>
			  </form>
			  
			    </div>
			  </div> <!-- / .pwd-lost -->
			</div>
		  </div>
		</div>  
	  
	</div> <!-- / .wrapper -->

app/views/pages/home.html.erb
<!--- The Logic of the home page is that it changes -->
<!--  depending on whether you are logged in or not -->

<% if user_signed_in? %>

    <%=    current_user.email %> is signed in.

	<!-- Wrapper -->
	<div class="wrapper">
	
	  <!-- Topic Header -->
	  <div class="topic">
	    <div class="container">
		  <div class="row">
		    <div class="col-sm-4">
		      <h3 class="primary-font">Start Game</h3>
		    </div>
		    <div class="col-sm-8">
		      <ol class="breadcrumb pull-right hidden-xs">
		        <li><a href="#">Home</a></li>
		        <li class="active">Start Gane</li>
		      </ol>
		    </div>
	      </div>
		</div>
	  </div>
            <%= form_for @matchup, url: "matchups/create" do |f| %>
<!--                <%= f.text_field :challenger %>
<%= f.text_field :challengee %> -->
                <%= f.collection_select(:team, Team.all.order(:name), :id, :name) %>
                <%= f.submit "Next" %>
             <% end %>
	  
	  <div class="container">
	    <div class="row">
		  <div class="col-sm-6 col-sm-offset-3">
			<div class="sign-form">
			  <h3 class="first-child">Start Game</h3>
			  <hr>

<!-- Here is the important Code for the Starting Game Form -->

			  <form role="form">
				<div class="form-group">
				  	<select class = "form-control">
                        <% @teams.each do |team| %>
                            <option><%=  team.name%> </option>
                        <% end %>
				  	</select>
				</div>
				<button type="submit" class="btn btn-color">Start Game</button>
			  </form>

<!-- Form End -->

			</div>
		  </div>
		</div> <!-- / .row -->
	  </div> <!-- / .container -->
	  
	</div> <!-- / .wrapper -->

<% else %>

	<!-- Wrapper -->
	<div class="wrapper">
	
	  <!-- Jumbotron -->
	  <div class="main-slideshow">
	    <div id="main-slideshow" class="carousel slide" data-ride="carousel">
		  <div class="carousel-inner">
		    <!-- Slide No 1 -->
		    <div class="item active">
			  <div class="jumbotron first">
				<div class="container">
				  <div class="row">
					<div class="col-sm-6">
					  <h1 class="animated slideInLeft">Beautiful Theme<br />You Can Tune Yourself</h1>
					  <p class="lead animated slideInLeft delay-1">An accurate and clean template for business projects.</p>
					  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-color animated slideInLeft delay-2" %>
					</div>
					<!--<div class="col-sm-6 hidden-xs">
					  <img class="img-responsive" src="img/imac.png" alt="...">
					</div>-->
				  </div>
				</div>
			  </div>
			</div> 
		  </div>
		  <!-- Controls -->
		  <a class="slideshow-arrow slideshow-arrow-prev bg-hover-color" href="#main-slideshow" data-slide="prev">
		    <i class="fa fa-angle-left"></i>
		  </a>
		  <a class="slideshow-arrow slideshow-arrow-next bg-hover-color" href="#main-slideshow" data-slide="next">
		    <i class="fa fa-angle-right"></i>
		  </a>
		</div>
	  </div>

<div class = "container">	

		<!-- Features -->
		<h2 class="headline text-color">
		  <span class="border-color">Main Features</span>
		</h2>
		<div class="row features">
		  <div class="col-sm-6">
			<h3 class="primary-font first-child">Easy to adjust for your needs with multiple color combinations.</h3>
			<p class="text-muted">
			  Nulla pretium libero interdum, tempus lorem non, rutrum diam. Quisque pellentesque diam sed pulvinar lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
			</p>
		  </div>
		  <div class="col-sm-6">
		    <img src="images/imac.png" class="img-responsive" alt="...">			
		  </div>
		</div> <!-- / .row -->
		<div class="divider"></div>
		<div class="row features last">
		  <div class="col-sm-6">
		    <div class="border-bottom"><img src="images/browser-cut.png" class="img-responsive" alt="..."></div>
		  </div>
		  <div class="col-sm-6">
			<h3 class="primary-font">Fifteen unique templates to take your site up and running in no time.</h3>
			<p class="text-muted">
			  Nulla pretium libero interdum, tempus lorem non, rutrum diam. Quisque pellentesque diam sed pulvinar lobortis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
			</p>
		  </div>
		</div> <!-- / .row -->
		
		<!-- Blog Posts -->
		<h2 class="headline text-color">
		  <span class="border-color">Read Our Blog</span>
		</h2>
		<div class="row recent-blogs">
		  <div class="col-sm-6">
			<div class="recent-blog">
			  <img src="images/photo-1.jpg" alt="...">
			  <div class="recent-blog-desc">
				<h3 class="primary-font">
				  <a href="blog-post.html">Sed lacinia suscipit lacus non sodales. Pellentesque lacinia ornare justo eu tincidunt. </a>
				</h3>
				<hr>
				<p class="text-muted">by John Doe</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nisi lorem, elementum sed feugiat ac, pharetra lacinia mi. Integer iaculis risus sed quam vehicula, sit amet lacinia sem rutrum. Integer ligula orci.</p>
                <%= link_to "Read More...", root_url, class: "btn btn-lg btn-color" %>
			  </div>
			</div>
		  </div>
		  <div class="col-sm-6">
			<div class="recent-blog">
			  <img src="images/photo-2.jpg" alt="...">
			  <div class="recent-blog-desc">
				<h3 class="primary-font">
				  <a href="blog-post.html">Nulla pretium libero interdum, tempus lorem non, rutrum diam. Lorem ipsum dolor sit amet.</a>
				</h3>
				<hr>
				<p class="text-muted">by John Doe</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc nisi lorem, elementum sed feugiat ac, pharetra lacinia mi. Integer iaculis risus sed quam vehicula, sit amet lacinia sem rutrum. Integer ligula orci.</p>
                <%= link_to "Read More...", root_url, class: "btn btn-lg btn-color" %>
			  </div>
			</div>
		  </div>
		</div> <!-- / .row -->
		
	  </div> <!-- / .container -->
	  
	</div> <!-- / .wrapper -->

</div><!-- / .container -->

<% end %>